// =========================================
// BAU MIND AI – Glavna JavaScript logika
// =========================================

// ==================== PREVODI ====================
const translations = {
    sr: { 
        voiceBadge:'Glasovne naredbe', sendDemo:'Pošalji demo', 
        navDashboard:'Dashboard', navProjects:'Projekti', navWorkers:'Radnici', 
        navRegister:'Prijava radnika', navFinance:'Finansije', navEmail:'Pošta', 
        navReport:'Izveštaj', activeProjects:'Aktivni projekti', of5:'od 5', 
        onPlan:'2 po planu', overBudget:'1 prekoračen', totalMargin:'Ukupna marža', 
        target:'Cilj: 22%', workersOnSite:'Radnici na terenu', of30:'od 30', 
        onSickLeave:'1 na bolovanju', monthlyRevenue:'Prihodi ovog meseca', 
        projection:'Projekcija: €156.000', materialChart:'📊 Potrošnja materijala', 
        urgentRecommendations:'🔥 Hitne preporuke', 
        rec1:'Kreuzberg – €24.500 prekoračenja', 
        rec2:'Mitte – nedostaje 1 radnik', 
        rec3:'Neukölln – ispod budžeta 7%', 
        rec4:'Zamenite dobavljača lepka – ušteda €4.200',
        rec5:'Novi radnik se prijavio za keramiku!',
        voiceCommand:'🗣️ Glasovna naredba (demo)', clickAndSpeak:'Klikni i govori', 
        voicePlaceholder:'Ovde će se prikazati vaša naredba...', 
        projectList:'📋 Lista projekata', add:'Dodaj', projectName:'Projekat', 
        budget:'Budžet', cost:'Trošak', status:'Status', action:'Akcija', 
        workersTitle:'👷 Radnici', name:'Ime', specialty:'Specijalnost', 
        hourlyRate:'Satnica', project:'Projekat', 
        incomeExpense:'💰 Prihodi / Rashodi', marginPerProject:'📈 Marža po projektu', 
        dailyCostEntry:'📅 Dnevni unos troškova', date:'Datum', item:'Stavka', 
        amount:'Iznos', dailyReport:'📄 Dnevni AI izveštaj', refresh:'Osveži', 
        contactUs:'Kontaktirajte nas', emailInbox:'📧 Pristigle poruke', 
        sender:'Pošiljalac', subject:'Naslov', aiAnalysis:'AI Analiza', 
        suggestedReply:'Predlog odgovora', sendReply:'Pošalji odgovor', 
        analyze:'🔍 AI analiza', close:'Zatvori', 
        registerTitle:'📝 Prijava novog radnika', submit:'Pošalji prijavu', 
        alertsTitle:'Alerti od novih prijava', noAlerts:'Nema novih alerta.',
        alertNewWorker:'🚨 Novi radnik sa hitnom strukom:',
        urgent:'HITNO!',
        active:'Aktivan'
    },
    hr: { 
        voiceBadge:'Glasovne naredbe', sendDemo:'Pošalji demo', 
        navDashboard:'Nadzorna ploča', navProjects:'Projekti', navWorkers:'Radnici', 
        navRegister:'Prijava radnika', navFinance:'Financije', navEmail:'Pošta', 
        navReport:'Izvještaj', activeProjects:'Aktivni projekti', of5:'od 5', 
        onPlan:'2 po planu', overBudget:'1 prekoračen', totalMargin:'Ukupna marža', 
        target:'Cilj: 22%', workersOnSite:'Radnici na terenu', of30:'od 30', 
        onSickLeave:'1 na bolovanju', monthlyRevenue:'Prihodi ovog mjeseca', 
        projection:'Projekcija: €156.000', materialChart:'📊 Potrošnja materijala', 
        urgentRecommendations:'🔥 Hitne preporuke', 
        rec1:'Kreuzberg – €24.500 prekoračenja', 
        rec2:'Mitte – nedostaje 1 radnik', 
        rec3:'Neukölln – ispod budžeta 7%', 
        rec4:'Zamijenite dobavljača ljepila – ušteda €4.200',
        rec5:'Novi radnik se prijavio za keramiku!',
        voiceCommand:'🗣️ Glasovna naredba (demo)', clickAndSpeak:'Klikni i govori', 
        voicePlaceholder:'Ovdje će se prikazati vaša naredba...', 
        projectList:'📋 Lista projekata', add:'Dodaj', projectName:'Projekat', 
        budget:'Budžet', cost:'Trošak', status:'Status', action:'Akcija', 
        workersTitle:'👷 Radnici', name:'Ime', specialty:'Specijalnost', 
        hourlyRate:'Satnica', project:'Projekat', 
        incomeExpense:'💰 Prihodi / Rashodi', marginPerProject:'📈 Marža po projektu', 
        dailyCostEntry:'📅 Dnevni unos troškova', date:'Datum', item:'Stavka', 
        amount:'Iznos', dailyReport:'📄 Dnevni AI izvještaj', refresh:'Osvježi', 
        contactUs:'Kontaktirajte nas', emailInbox:'📧 Pristigle poruke', 
        sender:'Pošiljatelj', subject:'Naslov', aiAnalysis:'AI Analiza', 
        suggestedReply:'Prijedlog odgovora', sendReply:'Pošalji odgovor', 
        analyze:'🔍 AI analiza', close:'Zatvori', 
        registerTitle:'📝 Prijava novog radnika', submit:'Pošalji prijavu', 
        alertsTitle:'Alerti od novih prijava', noAlerts:'Nema novih alerta.',
        alertNewWorker:'🚨 Novi radnik sa hitnom strukom:',
        urgent:'HITNO!',
        active:'Aktivan'
    },
    bs: { 
        voiceBadge:'Glasovne naredbe', sendDemo:'Pošalji demo', 
        navDashboard:'Kontrolna tabla', navProjects:'Projekti', navWorkers:'Radnici', 
        navRegister:'Prijava radnika', navFinance:'Finansije', navEmail:'Pošta', 
        navReport:'Izvještaj', activeProjects:'Aktivni projekti', of5:'od 5', 
        onPlan:'2 po planu', overBudget:'1 prekoračen', totalMargin:'Ukupna marža', 
        target:'Cilj: 22%', workersOnSite:'Radnici na terenu', of30:'od 30', 
        onSickLeave:'1 na bolovanju', monthlyRevenue:'Prihodi ovog mjeseca', 
        projection:'Projekcija: €156.000', materialChart:'📊 Potrošnja materijala', 
        urgentRecommendations:'🔥 Hitne preporuke', 
        rec1:'Kreuzberg – €24.500 prekoračenja', 
        rec2:'Mitte – nedostaje 1 radnik', 
        rec3:'Neukölln – ispod budžeta 7%', 
        rec4:'Zamijenite dobavljača ljepila – ušteda €4.200',
        rec5:'Novi radnik se prijavio za keramiku!',
        voiceCommand:'🗣️ Glasovna naredba (demo)', clickAndSpeak:'Klikni i govori', 
        voicePlaceholder:'Ovdje će se prikazati vaša naredba...', 
        projectList:'📋 Lista projekata', add:'Dodaj', projectName:'Projekat', 
        budget:'Budžet', cost:'Trošak', status:'Status', action:'Akcija', 
        workersTitle:'👷 Radnici', name:'Ime', specialty:'Specijalnost', 
        hourlyRate:'Satnica', project:'Projekat', 
        incomeExpense:'💰 Prihodi / Rashodi', marginPerProject:'📈 Marža po projektu', 
        dailyCostEntry:'📅 Dnevni unos troškova', date:'Datum', item:'Stavka', 
        amount:'Iznos', dailyReport:'📄 Dnevni AI izvještaj', refresh:'Osveži', 
        contactUs:'Kontaktirajte nas', emailInbox:'📧 Pristigle poruke', 
        sender:'Pošiljalac', subject:'Naslov', aiAnalysis:'AI Analiza', 
        suggestedReply:'Predlog odgovora', sendReply:'Pošalji odgovor', 
        analyze:'🔍 AI analiza', close:'Zatvori', 
        registerTitle:'📝 Prijava novog radnika', submit:'Pošalji prijavu', 
        alertsTitle:'Alerti od novih prijava', noAlerts:'Nema novih alerta.',
        alertNewWorker:'🚨 Novi radnik sa hitnom strukom:',
        urgent:'HITNO!',
        active:'Aktivan'
    },
    mk: { 
        voiceBadge:'Гласовни команди', sendDemo:'Испрати демо', 
        navDashboard:'Контролна табла', navProjects:'Проекти', navWorkers:'Работници', 
        navRegister:'Пријава на работник', navFinance:'Финансии', navEmail:'Пошта', 
        navReport:'Извештај', activeProjects:'Активни проекти', of5:'од 5', 
        onPlan:'2 по план', overBudget:'1 пречекорен', totalMargin:'Вкупна маржа', 
        target:'Цел: 22%', workersOnSite:'Работници на терен', of30:'од 30', 
        onSickLeave:'1 на боледување', monthlyRevenue:'Приходи овој месец', 
        projection:'Проекција: €156.000', materialChart:'📊 Потрошувачка на материјал', 
        urgentRecommendations:'🔥 Итни препораки', 
        rec1:'Кројцберг – €24.500 пречекорувања', 
        rec2:'Мите – недостасува 1 работник', 
        rec3:'Нојкелн – под буџетот 7%', 
        rec4:'Замените го добавувачот на лепак – заштеда €4.200',
        rec5:'Нов работник се пријави за керамика!',
        voiceCommand:'🗣️ Гласовна команда (демо)', clickAndSpeak:'Кликни и зборувај', 
        voicePlaceholder:'Овде ќе се прикаже вашата команда...', 
        projectList:'📋 Листа на проекти', add:'Додај', projectName:'Проект', 
        budget:'Буџет', cost:'Трошок', status:'Статус', action:'Акција', 
        workersTitle:'👷 Работници', name:'Име', specialty:'Специјалност', 
        hourlyRate:'Саатница', project:'Проект', 
        incomeExpense:'💰 Приходи / Расходи', marginPerProject:'📈 Маржа по проект', 
        dailyCostEntry:'📅 Дневен внес на трошоци', date:'Датум', item:'Ставка', 
        amount:'Износ', dailyReport:'📄 Дневен AI извештај', refresh:'Освежи', 
        contactUs:'Контактирајте не', emailInbox:'📧 Пристигнати пораки', 
        sender:'Испраќач', subject:'Наслов', aiAnalysis:'AI Анализа', 
        suggestedReply:'Предлог за одговор', sendReply:'Испрати одговор', 
        analyze:'🔍 AI анализа', close:'Затвори', 
        registerTitle:'📝 Пријава на нов работник', submit:'Испрати пријава', 
        alertsTitle:'Алерти од нови пријави', noAlerts:'Нема нови алерти.',
        alertNewWorker:'🚨 Нов работник со итна струка:',
        urgent:'ИТНО!',
        active:'Активен'
    },
    de: { 
        voiceBadge:'Sprachbefehle', sendDemo:'Demo senden', 
        navDashboard:'Dashboard', navProjects:'Projekte', navWorkers:'Arbeiter', 
        navRegister:'Arbeiter Anmeldung', navFinance:'Finanzen', navEmail:'Post', 
        navReport:'Bericht', activeProjects:'Aktive Projekte', of5:'von 5', 
        onPlan:'2 im Plan', overBudget:'1 überschritten', totalMargin:'Gesamtmarge', 
        target:'Ziel: 22%', workersOnSite:'Arbeiter vor Ort', of30:'von 30', 
        onSickLeave:'1 krankgeschrieben', monthlyRevenue:'Einnahmen diesen Monat', 
        projection:'Prognose: €156.000', materialChart:'📊 Materialverbrauch', 
        urgentRecommendations:'🔥 Dringende Empfehlungen', 
        rec1:'Kreuzberg – €24.500 Überschreitung', 
        rec2:'Mitte – 1 Arbeiter fehlt', 
        rec3:'Neukölln – 7% unter Budget', 
        rec4:'Wechseln Sie den Klebstofflieferanten – Einsparung €4.200',
        rec5:'Neuer Arbeiter für Keramik angemeldet!',
        voiceCommand:'🗣️ Sprachbefehl (Demo)', clickAndSpeak:'Klicken und sprechen', 
        voicePlaceholder:'Hier wird Ihr Befehl angezeigt...', 
        projectList:'📋 Projektliste', add:'Hinzufügen', projectName:'Projekt', 
        budget:'Budget', cost:'Kosten', status:'Status', action:'Aktion', 
        workersTitle:'👷 Arbeiter', name:'Name', specialty:'Spezialisierung', 
        hourlyRate:'Stundensatz', project:'Projekt', 
        incomeExpense:'💰 Einnahmen / Ausgaben', marginPerProject:'📈 Marge pro Projekt', 
        dailyCostEntry:'📅 Tägliche Kostenerfassung', date:'Datum', item:'Position', 
        amount:'Betrag', dailyReport:'📄 Täglicher AI-Bericht', refresh:'Aktualisieren', 
        contactUs:'Kontaktieren Sie uns', emailInbox:'📧 Posteingang', 
        sender:'Absender', subject:'Betreff', aiAnalysis:'KI-Analyse', 
        suggestedReply:'Antwortvorschlag', sendReply:'Antwort senden', 
        analyze:'🔍 KI-Analyse', close:'Schließen', 
        registerTitle:'📝 Neue Arbeiter Anmeldung', submit:'Anmeldung senden', 
        alertsTitle:'Alarme von neuen Anmeldungen', noAlerts:'Keine neuen Alarme.',
        alertNewWorker:'🚨 Neuer Arbeiter mit dringendem Beruf:',
        urgent:'DRINGEND!',
        active:'Aktiv'
    }
};

// ==================== GLOBALNI PODACI ====================
let currentLang = 'sr';
let radnici = [];
let hitneStruke = ['zidar', 'elektricar', 'keramicar'];
let alerti = [];
let idCounter = 1;

let projects = [
    { id: 1, name: 'Stanovi Kreuzberg', budget: 124000, cost: 148500 },
    { id: 2, name: 'Kancelarije Mitte', budget: 78000, cost: 82000 },
    { id: 3, name: 'Škola Neukölln', budget: 175000, cost: 163000 }
];

let workers = [
    { id: 1, name: 'Mirko Petrović', spec: 'Keramika+fuge', rate: 28, project: 'Kreuzberg', free: false },
    { id: 2, name: 'Zoran Horvat', spec: 'Keramika', rate: 25, project: 'Kreuzberg', free: false },
    { id: 3, name: 'Ana Kovačević', spec: 'Keramika+pločice', rate: 27, project: 'Mitte', free: false },
    { id: 4, name: 'Marko Schröder', spec: 'Keramika+fuge', rate: 29, project: '', free: true }
];

let costs = [
    { date: '2026-09-
